services:
  postgres:
    image: postgres:16
    container_name: poll-postgres
    environment:
      POSTGRES_DB: poll_system
      POSTGRES_USER: poll_user
      POSTGRES_PASSWORD: poll_pass
      TZ: Europe/Rome
    ports:
      - "5434:5432"
    volumes:
      - poll_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: poll-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  poll_pgdata:
