spring:
  application:
    name: pollsystem

  datasource:
    url: jdbc:postgresql://localhost:5434/poll_system
    username: poll_user
    password: poll_pass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    schemas: public
    default-schema: public
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  jwt:
    secret: "MDEyMzQ1Njc4OUFCQ0RFRjAxMjM0NTY3ODlBQkNERUY="
    expiration-minutes: 30

  queue:
    poll-winner-mail: poll.winner.mail
