spring:
  application:
    name: poll-batch-service

  datasource:
    url: jdbc:postgresql://localhost:5434/poll_system
    username: poll_user
    password: poll_pass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  batch:
    limit: 200

  queue:
    poll-winner-mail: poll.winner.mail
